// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: api/system/user/service/v1/system_user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 任意类型
	Data *anypb.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GlobalResponse) Reset() {
	*x = GlobalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalResponse) ProtoMessage() {}

func (x *GlobalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalResponse.ProtoReflect.Descriptor instead.
func (*GlobalResponse) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GlobalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GlobalResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSystemUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile   string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
}

func (x *CreateSystemUserRequest) Reset() {
	*x = CreateSystemUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemUserRequest) ProtoMessage() {}

func (x *CreateSystemUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemUserRequest.ProtoReflect.Descriptor instead.
func (*CreateSystemUserRequest) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSystemUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateSystemUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateSystemUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateSystemUserRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type CreateSystemUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSystemUserReply) Reset() {
	*x = CreateSystemUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemUserReply) ProtoMessage() {}

func (x *CreateSystemUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemUserReply.ProtoReflect.Descriptor instead.
func (*CreateSystemUserReply) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{2}
}

type UpdateSystemUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSystemUserRequest) Reset() {
	*x = UpdateSystemUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSystemUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemUserRequest) ProtoMessage() {}

func (x *UpdateSystemUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateSystemUserRequest) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{3}
}

type UpdateSystemUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSystemUserReply) Reset() {
	*x = UpdateSystemUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSystemUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemUserReply) ProtoMessage() {}

func (x *UpdateSystemUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemUserReply.ProtoReflect.Descriptor instead.
func (*UpdateSystemUserReply) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{4}
}

type DeleteSystemUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSystemUserRequest) Reset() {
	*x = DeleteSystemUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSystemUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSystemUserRequest) ProtoMessage() {}

func (x *DeleteSystemUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSystemUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteSystemUserRequest) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{5}
}

type DeleteSystemUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSystemUserReply) Reset() {
	*x = DeleteSystemUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSystemUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSystemUserReply) ProtoMessage() {}

func (x *DeleteSystemUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSystemUserReply.ProtoReflect.Descriptor instead.
func (*DeleteSystemUserReply) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{6}
}

type GetSystemUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSystemUserRequest) Reset() {
	*x = GetSystemUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemUserRequest) ProtoMessage() {}

func (x *GetSystemUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemUserRequest.ProtoReflect.Descriptor instead.
func (*GetSystemUserRequest) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetSystemUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSystemUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Mobile   string `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
}

func (x *GetSystemUserReply) Reset() {
	*x = GetSystemUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemUserReply) ProtoMessage() {}

func (x *GetSystemUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemUserReply.ProtoReflect.Descriptor instead.
func (*GetSystemUserReply) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetSystemUserReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSystemUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetSystemUserReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetSystemUserReply) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetSystemUserReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type ListSystemUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSystemUserRequest) Reset() {
	*x = ListSystemUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemUserRequest) ProtoMessage() {}

func (x *ListSystemUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemUserRequest.ProtoReflect.Descriptor instead.
func (*ListSystemUserRequest) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{9}
}

type ListSystemUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSystemUserReply) Reset() {
	*x = ListSystemUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSystemUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSystemUserReply) ProtoMessage() {}

func (x *ListSystemUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_user_service_v1_system_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSystemUserReply.ProtoReflect.Descriptor instead.
func (*ListSystemUserReply) Descriptor() ([]byte, []int) {
	return file_api_system_user_service_v1_system_user_proto_rawDescGZIP(), []int{10}
}

var File_api_system_user_service_v1_system_user_proto protoreflect.FileDescriptor

var file_api_system_user_service_v1_system_user_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x85, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0x17, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xad, 0x05, 0x0a, 0x0a, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x9d, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x33, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a,
	0x22, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x7a, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x33, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x7a, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x90, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x24, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x74, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x12, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_system_user_service_v1_system_user_proto_rawDescOnce sync.Once
	file_api_system_user_service_v1_system_user_proto_rawDescData = file_api_system_user_service_v1_system_user_proto_rawDesc
)

func file_api_system_user_service_v1_system_user_proto_rawDescGZIP() []byte {
	file_api_system_user_service_v1_system_user_proto_rawDescOnce.Do(func() {
		file_api_system_user_service_v1_system_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_system_user_service_v1_system_user_proto_rawDescData)
	})
	return file_api_system_user_service_v1_system_user_proto_rawDescData
}

var file_api_system_user_service_v1_system_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_system_user_service_v1_system_user_proto_goTypes = []any{
	(*GlobalResponse)(nil),          // 0: api.system.user.service.v1.globalResponse
	(*CreateSystemUserRequest)(nil), // 1: api.system.user.service.v1.CreateSystemUserRequest
	(*CreateSystemUserReply)(nil),   // 2: api.system.user.service.v1.CreateSystemUserReply
	(*UpdateSystemUserRequest)(nil), // 3: api.system.user.service.v1.UpdateSystemUserRequest
	(*UpdateSystemUserReply)(nil),   // 4: api.system.user.service.v1.UpdateSystemUserReply
	(*DeleteSystemUserRequest)(nil), // 5: api.system.user.service.v1.DeleteSystemUserRequest
	(*DeleteSystemUserReply)(nil),   // 6: api.system.user.service.v1.DeleteSystemUserReply
	(*GetSystemUserRequest)(nil),    // 7: api.system.user.service.v1.GetSystemUserRequest
	(*GetSystemUserReply)(nil),      // 8: api.system.user.service.v1.GetSystemUserReply
	(*ListSystemUserRequest)(nil),   // 9: api.system.user.service.v1.ListSystemUserRequest
	(*ListSystemUserReply)(nil),     // 10: api.system.user.service.v1.ListSystemUserReply
	(*anypb.Any)(nil),               // 11: google.protobuf.Any
}
var file_api_system_user_service_v1_system_user_proto_depIdxs = []int32{
	11, // 0: api.system.user.service.v1.globalResponse.data:type_name -> google.protobuf.Any
	1,  // 1: api.system.user.service.v1.SystemUser.CreateSystemUser:input_type -> api.system.user.service.v1.CreateSystemUserRequest
	3,  // 2: api.system.user.service.v1.SystemUser.UpdateSystemUser:input_type -> api.system.user.service.v1.UpdateSystemUserRequest
	5,  // 3: api.system.user.service.v1.SystemUser.DeleteSystemUser:input_type -> api.system.user.service.v1.DeleteSystemUserRequest
	7,  // 4: api.system.user.service.v1.SystemUser.GetSystemUser:input_type -> api.system.user.service.v1.GetSystemUserRequest
	9,  // 5: api.system.user.service.v1.SystemUser.ListSystemUser:input_type -> api.system.user.service.v1.ListSystemUserRequest
	2,  // 6: api.system.user.service.v1.SystemUser.CreateSystemUser:output_type -> api.system.user.service.v1.CreateSystemUserReply
	4,  // 7: api.system.user.service.v1.SystemUser.UpdateSystemUser:output_type -> api.system.user.service.v1.UpdateSystemUserReply
	6,  // 8: api.system.user.service.v1.SystemUser.DeleteSystemUser:output_type -> api.system.user.service.v1.DeleteSystemUserReply
	8,  // 9: api.system.user.service.v1.SystemUser.GetSystemUser:output_type -> api.system.user.service.v1.GetSystemUserReply
	10, // 10: api.system.user.service.v1.SystemUser.ListSystemUser:output_type -> api.system.user.service.v1.ListSystemUserReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_system_user_service_v1_system_user_proto_init() }
func file_api_system_user_service_v1_system_user_proto_init() {
	if File_api_system_user_service_v1_system_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_system_user_service_v1_system_user_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GlobalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSystemUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateSystemUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateSystemUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateSystemUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSystemUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSystemUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetSystemUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetSystemUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListSystemUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_system_user_service_v1_system_user_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListSystemUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_system_user_service_v1_system_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_user_service_v1_system_user_proto_goTypes,
		DependencyIndexes: file_api_system_user_service_v1_system_user_proto_depIdxs,
		MessageInfos:      file_api_system_user_service_v1_system_user_proto_msgTypes,
	}.Build()
	File_api_system_user_service_v1_system_user_proto = out.File
	file_api_system_user_service_v1_system_user_proto_rawDesc = nil
	file_api_system_user_service_v1_system_user_proto_goTypes = nil
	file_api_system_user_service_v1_system_user_proto_depIdxs = nil
}
