// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/gopherxin/goadmin/app/internal/biz"
	"github.com/gopherxin/goadmin/app/internal/conf"
	"github.com/gopherxin/goadmin/app/internal/data"
	"github.com/gopherxin/goadmin/app/internal/server"
	"github.com/gopherxin/goadmin/app/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	systemUserRepo := data.NewSystemUserRepo(dataData, logger)
	systemUserUseCase := biz.NewSystemUserUseCase(systemUserRepo, logger)
	systemUserService := service.NewSystemUserService(systemUserUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, systemUserService, logger)
	httpServer := server.NewHTTPServer(confServer, systemUserService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
